# workflow name
name: Release

# on events
on:
  release:
    types: 
        - created

# jobs
jobs:
  generate:
    name: Generate cross-platform builds
    runs-on: ubuntu-latest
    steps:
      # Checkout the repo
      - name: Checkout the repository
        uses: actions/checkout@v2
        
      # Generade build files
      - name: Generate build artifacts
        uses: thatisuday/go-cross-build@master
        with:
            platforms: 'linux/386, linux/amd64, linux/arm, linux/arm64, darwin/amd64'
            package: ""
            name: 'logGrouper'
            compress: 'true'
            dest: 'dist'
      
      # upload files
      - name: Upload build-artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: "./dist/*.tar.gz"
